"""Hermes tool registrations for Graph-and-Loop orchestration."""
import json
from .control_plane import plane

def _out(value): return json.dumps(value,ensure_ascii=False)
def register_tools(ctx):
    ctx.register_tool("graph_loop_status","graph_loop",{"name":"graph_loop_status","description":"Return Graph-and-Loop control-plane status.","parameters":{"type":"object","properties":{}}},lambda args,**kw:_out(plane.status()),description="Inspect the Graph-and-Loop control plane.",emoji="🕸️")
    ctx.register_tool("graph_create","graph_loop",{"name":"graph_create","description":"Create a master-controlled worker graph with explicit definition-of-done criteria.","parameters":{"type":"object","properties":{"goal":{"type":"string"},"definition_of_done":{"type":"array","items":{"type":"string"}},"master_agent":{"type":"string"},"workers":{"type":"array","items":{"type":"string"}},"nodes":{"type":"array"}},"required":["goal","definition_of_done"]}},lambda a,**kw:_out(plane.create(a.get("goal",""),a.get("definition_of_done",[]),a.get("master_agent","ceo"),a.get("workers",[]),a.get("nodes",[]))),description="Create a persistent Graph-and-Loop plan.",emoji="🧠")
    ctx.register_tool("graph_runnable_nodes","graph_loop",{"name":"graph_runnable_nodes","description":"List worker nodes whose dependencies are complete.","parameters":{"type":"object","properties":{"graph_id":{"type":"string"}},"required":["graph_id"]}},lambda a,**kw:_out({"nodes":plane.runnable(a["graph_id"])}),description="Find the next executable worker nodes.",emoji="▶️")
    ctx.register_tool("graph_claim_node","graph_loop",{"name":"graph_claim_node","description":"Claim a runnable worker node.","parameters":{"type":"object","properties":{"graph_id":{"type":"string"},"node_id":{"type":"string"},"agent_id":{"type":"string"}},"required":["graph_id","node_id"]}},lambda a,**kw:_out(plane.claim(a["graph_id"],a["node_id"],a.get("agent_id",""))),description="Claim a graph work item.",emoji="🛠️")
    ctx.register_tool("graph_complete_node","graph_loop",{"name":"graph_complete_node","description":"Submit worker output and evidence for a graph node.","parameters":{"type":"object","properties":{"graph_id":{"type":"string"},"node_id":{"type":"string"},"result":{},"evidence":{"type":"array","items":{"type":"string"}},"status":{"type":"string"}},"required":["graph_id","node_id","result"]}},lambda a,**kw:_out(plane.complete(a["graph_id"],a["node_id"],a.get("result"),a.get("evidence",[]),a.get("status","complete"))),description="Record evidence-backed worker completion.",emoji="✅")
    ctx.register_tool("graph_verify","graph_loop",{"name":"graph_verify","description":"Run the strict verifier gate against all definition-of-done criteria.","parameters":{"type":"object","properties":{"graph_id":{"type":"string"},"checks":{"type":"array"}},"required":["graph_id","checks"]}},lambda a,**kw:_out(plane.verify(a["graph_id"],a.get("checks",[]))),description="Approve or loop a graph based on evidence.",emoji="🔎")
    ctx.register_tool("agent_ping","graph_loop",{"name":"agent_ping","description":"Queue an asynchronous inter-agent ping to two or more recipients.","parameters":{"type":"object","properties":{"sender":{"type":"string"},"recipients":{"type":"array","items":{"type":"string"}},"message":{"type":"string"},"graph_id":{"type":"string"},"node_id":{"type":"string"},"priority":{"type":"string"}},"required":["recipients","message"]}},lambda a,**kw:_out(plane.ping(a.get("sender","system"),a.get("recipients",[]),a.get("message",""),a.get("graph_id",""),a.get("node_id",""),a.get("priority","normal"))),description="Send a durable asynchronous wake signal between agents.",emoji="📡")
