"""Hermes Tag additive governance, identity, context, and continuity kernel."""

from .bridge import identity_from_session_source, surface_from_session_source
from .capability import BUILTIN_CAPABILITIES, CapabilityRegistry
from .config import HermesTagConfig, database_path, profile_state_directory
from .continuity import ContinuityRecord, ContinuityStore
from .enforcement import LeaseAuthority
from .errors import (
    ApprovalRequired,
    BudgetExceeded,
    ConfigurationError,
    HermesTagError,
    IdentityConflict,
    IncompleteScope,
    LeaseError,
    LeaseExpired,
    LeaseReplay,
    LeaseTampered,
    ObligationError,
    PolicyDenied,
    ReceiptChainError,
    ReplayDetected,
    StaleWriteError,
    StorageError,
    UnknownIdentity,
)
from .identity import IdentityStore
from .kernel import AuthorizationResult, CompletionResult, HermesTagKernel
from .ledger import (
    BudgetLimits,
    BudgetReservation,
    HermesTagLedger,
    ReceiptRecord,
)
from .middleware import AdmissionResult, TurnAdmissionMiddleware
from .model import (
    ActionIntent,
    ApprovalGrant,
    CapabilityDefinition,
    CapabilityLease,
    ContextBundle,
    ContinuityEnvelope,
    ContinuityMode,
    DecisionOutcome,
    ExternalIdentity,
    Fact,
    PolicyDecision,
    Principal,
    RiskLevel,
    ScopeRef,
    Sensitivity,
    SurfaceRef,
    TurnAdmission,
    arguments_digest,
    canonical_digest,
    canonical_json,
    new_id,
    parse_utc,
    utc_now,
    utc_text,
)
from .obligations import (
    BUILTIN_OBLIGATIONS,
    ObligationDefinition,
    ObligationPhase,
    ObligationRegistry,
)
from .omniscience import FactStore
from .policy import PolicyEngine, PolicyEvaluation, PolicyRule
from .runtime import (
    RuntimeAuthority,
    bind_admission,
    bind_authority,
    bind_decision,
    bind_lease,
    capture_authority,
    clear_runtime_context,
    current_admission,
    current_decision,
    current_lease,
)
from .scopes import (
    require_scope_fields,
    scope_from_surface,
    scope_is_within,
    scope_matches,
    scope_redacted,
)
from .service import HermesTagService, ShadowAdmissionOutcome

__all__ = [
    "ActionIntent",
    "ApprovalRequired",
    "BudgetExceeded",
    "ConfigurationError",
    "HermesTagError",
    "IdentityConflict",
    "IncompleteScope",
    "LeaseError",
    "LeaseExpired",
    "LeaseReplay",
    "LeaseTampered",
    "ObligationError",
    "PolicyDenied",
    "ReceiptChainError",
    "ReplayDetected",
    "StaleWriteError",
    "StorageError",
    "UnknownIdentity",
    "AdmissionResult",
    "ApprovalGrant",
    "AuthorizationResult",
    "BUILTIN_CAPABILITIES",
    "BUILTIN_OBLIGATIONS",
    "BudgetLimits",
    "BudgetReservation",
    "CapabilityDefinition",
    "CapabilityLease",
    "CapabilityRegistry",
    "CompletionResult",
    "ContextBundle",
    "ContinuityEnvelope",
    "ContinuityMode",
    "ContinuityRecord",
    "ContinuityStore",
    "DecisionOutcome",
    "ExternalIdentity",
    "Fact",
    "FactStore",
    "HermesTagConfig",
    "HermesTagKernel",
    "HermesTagLedger",
    "HermesTagService",
    "IdentityStore",
    "LeaseAuthority",
    "ObligationDefinition",
    "ObligationPhase",
    "ObligationRegistry",
    "PolicyDecision",
    "PolicyEngine",
    "PolicyEvaluation",
    "PolicyRule",
    "Principal",
    "ReceiptRecord",
    "RiskLevel",
    "RuntimeAuthority",
    "ScopeRef",
    "Sensitivity",
    "ShadowAdmissionOutcome",
    "SurfaceRef",
    "TurnAdmission",
    "TurnAdmissionMiddleware",
    "arguments_digest",
    "bind_admission",
    "bind_authority",
    "bind_decision",
    "bind_lease",
    "canonical_digest",
    "canonical_json",
    "capture_authority",
    "clear_runtime_context",
    "current_admission",
    "current_decision",
    "current_lease",
    "database_path",
    "identity_from_session_source",
    "new_id",
    "parse_utc",
    "profile_state_directory",
    "require_scope_fields",
    "scope_from_surface",
    "scope_is_within",
    "scope_matches",
    "scope_redacted",
    "surface_from_session_source",
    "utc_now",
    "utc_text",
]
