"""The recommendation decision table — the reviewable matrix.

The recommendation itself is DERIVED (catalog.recommended_entry: best
quality among resident entries clearing the pleasant speed floor, else
fastest resident). Spilled models stay browseable but are never automatic
recommendations, so nobody hand-maintains per-hardware-class picks.
This table pins the model and reason across discrete and unified memory
classes so changes to the recommendation remain reviewable.

These are decision pins, not change-detectors: each cell is a choice a
human approved, exactly like a golden file. When a cell flips on
purpose, update it in the same commit and say why. When one flips by
surprise, that is the test doing its job.

Budgets mirror hardware.probe_budget's planning-mode shapes (margins,
UMA headroom) so the cells match what a real machine of that class
resolves.
"""

from __future__ import annotations

import pytest

from hermes_cli.local_runtime.catalog import (
    AssetFile,
    CatalogEntry,
    CATALOG,
    PLEASANT_FLOOR_TOK_S,
    QuantVariant,
    predicted_agent_turn_latency_s,
    predicted_decode_tok_s,
    recommended_entry,
    select_variant,
)
from hermes_cli.local_runtime.estimator import HardwareBudget

_GIB = 1 << 30


def _discrete(size_gb: int) -> HardwareBudget:
    total = size_gb * _GIB
    margin = max(2 * _GIB, int(total * 0.09))
    return HardwareBudget(usable_vram_bytes=max(0, total - margin),
                          total_device_bytes=total,
                          ram_available_bytes=64 * _GIB, uma=False)


def _unified(size_gb: int) -> HardwareBudget:
    total = size_gb * _GIB
    return HardwareBudget(usable_vram_bytes=int(total * 0.80),
                          total_device_bytes=total,
                          ram_available_bytes=0, uma=True)


# The decision table. Cells were generated by the resolver and then
# reviewed as editorial decisions:
#
#   VRAM | discrete                | unified
#   -----+-------------------------+------------------------
#     8  | (no recommendation)      | (none fits)
#    16  | (no recommendation)      | (none fits)
#    24  | qwen3.8-27b             | (none fits)
#    32  | qwen3.8-27b             | qwen3.6-35b-a3b
#    48  | qwen3.8-27b             | qwen3.6-35b-a3b
#    96  | qwen3.8-27b             | qwen3.6-35b-a3b
#   128  | qwen3.8-flash-next      | qwen3.6-35b-a3b
#   256  | qwen3.8-flash-next      | qwen3.8-flash-next
#   512  | qwen3.8-flash-next      | qwen3.8-flash-next
#
# Reading guide for reviewers:
# - Discrete <=16 GB: nothing runs resident; no automatic recommendation.
#   Browse remains available for explicit spill choices.
# - Discrete 24-96 GB: the 27B is the flagship experience — dense reads
#   at ~1 TB/s clear the floor easily, so quality decides.
# - Discrete/unified where Flash Next fits resident (128 GB discrete,
#   256+ GB unified): the frontier model is the pick — highest quality,
#   and its sparse decode clears the floor even at UMA bandwidth
#   (~24 tok/s predicted at 210 GB/s).
# - Unified 32-128 GB — the Spark class, the reason this resolver
#   exists: the dense 27B predicts ~13 tok/s at UMA bandwidth (below
#   the pleasant floor), so the 35B-A3B (~60 tok/s) wins.
# - Unified <=24 GB: no entry passes the physics check inside the UMA
#   budget (spilling is impossible on UMA by construction — the pool IS
#   the RAM). The pane's browse flow is the path for those machines
#   until a small catalog entry lands (revisit when one does).
DECISION_TABLE = [
    (8, "discrete", None, None),
    (8, "unified", None, None),
    (16, "discrete", None, None),
    (16, "unified", None, None),
    (24, "discrete", "qwen3.8-27b", "best-quality-resident"),
    (24, "unified", None, None),
    (32, "discrete", "qwen3.8-27b", "best-quality-resident"),
    (32, "unified", "qwen3.6-35b-a3b", "speed-gated-quality"),
    (48, "discrete", "qwen3.8-27b", "best-quality-resident"),
    (48, "unified", "qwen3.6-35b-a3b", "speed-gated-quality"),
    (96, "discrete", "qwen3.8-27b", "best-quality-resident"),
    (96, "unified", "qwen3.6-35b-a3b", "speed-gated-quality"),
    (128, "discrete", "qwen3.8-flash-next", "best-quality-resident"),
    (128, "unified", "qwen3.6-35b-a3b", "speed-gated-quality"),
    (256, "discrete", "qwen3.8-flash-next", "best-quality-resident"),
    (256, "unified", "qwen3.8-flash-next", "best-quality-resident"),
    (512, "discrete", "qwen3.8-flash-next", "best-quality-resident"),
    (512, "unified", "qwen3.8-flash-next", "best-quality-resident"),
]


@pytest.mark.parametrize(
    ("size_gb", "kind", "expected", "expected_reason"),
    DECISION_TABLE,
    ids=[f"{s}GB-{k}" for s, k, _, _ in DECISION_TABLE])
def test_recommendation_decision_table(size_gb, kind, expected, expected_reason):
    """Pins the pick AND its reason per cell: the reason is user-facing
    (the Recommended badge's tooltip), so a cell whose rationale flips
    without the pick flipping is still a review-worthy change."""
    budget = _discrete(size_gb) if kind == "discrete" else _unified(size_gb)
    picked = recommended_entry(budget)
    if expected is None:
        assert picked is None
    else:
        assert picked is not None
        assert (picked[0].id, picked[1]) == (expected, expected_reason)


# ── invariants behind the table (survive catalog changes) ──


def test_every_entry_carries_the_recommendation_axes():
    """quality and decode_fraction are authoring requirements: an entry
    without them silently loses every quality comparison (quality=0) or
    prices as dense (decode_fraction=1.0)."""
    for entry in CATALOG:
        assert entry.quality > 0, f"{entry.id} has no quality ordering"
        assert 0.0 < entry.decode_fraction <= 1.0, entry.id
        if not entry.moe:
            assert entry.decode_fraction == 1.0, (
                f"{entry.id} is dense — it reads every weight per token")


def test_unified_never_recommends_a_below_floor_dense_model():
    """The Spark rule, as an invariant: whatever the catalog holds, a
    unified-memory machine must not be told to run a model whose
    predicted decode is below the pleasant floor while a resident
    alternative clears it."""
    budget = _unified(128)
    pick = recommended_entry(budget)[0].id
    assert pick is not None
    entry = next(e for e in CATALOG if e.id == pick)
    choice = select_variant(entry, budget)
    assert choice is not None and choice.zero_spill
    clears = [
        e for e in CATALOG
        if (c := select_variant(e, budget)) is not None and c.zero_spill
        and predicted_decode_tok_s(e, c.variant, budget) >= PLEASANT_FLOOR_TOK_S
    ]
    if clears:
        assert predicted_decode_tok_s(entry, choice.variant, budget) >= PLEASANT_FLOOR_TOK_S


def test_quality_decides_where_speed_permits():
    """On big discrete hardware every resident entry clears the floor, so
    the pick must be the highest-quality fitting entry — the axis that
    justifies carrying an editorial field at all."""
    budget = _discrete(512)
    pick = recommended_entry(budget)[0].id
    resident = [
        e for e in CATALOG
        if (c := select_variant(e, budget)) is not None and c.zero_spill
    ]
    assert pick == max(resident, key=lambda e: e.quality).id


def _test_entry(*, entry_id: str, quality: int, size_gb: int,
                prefill_tok_s: float | None = None) -> CatalogEntry:
    return CatalogEntry(
        id=entry_id, display_name=entry_id, description="test", repo="test/repo",
        variants=(QuantVariant("Q4", (AssetFile("model.gguf", size_gb * _GIB),)),),
        n_ctx_train=262144, full_layers=1, recurrent_layers=0, per_layer_f16=1,
        quality=quality, prefill_tok_s=prefill_tok_s,
    )


def test_prefill_aware_latency_prices_an_agent_turn_not_just_decode():
    """A long prompt makes a slow prefill materially visible in the estimate."""
    budget = _discrete(128)
    fast = _test_entry(entry_id="fast-prefill", quality=1, size_gb=10, prefill_tok_s=1_000)
    slow = _test_entry(entry_id="slow-prefill", quality=1, size_gb=1, prefill_tok_s=10)

    fast_latency = predicted_agent_turn_latency_s(
        fast, fast.variants[0], budget, input_tokens=32_768)
    slow_latency = predicted_agent_turn_latency_s(
        slow, slow.variants[0], budget, input_tokens=32_768)

    assert fast_latency is not None
    assert slow_latency is not None
    assert slow_latency > fast_latency * 20


def test_prefill_dominated_turn_gates_a_higher_quality_model():
    """Quality cannot recommend a model whose measured prompt cost is unpleasant."""
    budget = _discrete(128)
    fast = _test_entry(entry_id="fast-prefill", quality=50, size_gb=10, prefill_tok_s=1_000)
    slow = _test_entry(entry_id="slow-prefill", quality=100, size_gb=1, prefill_tok_s=10)

    picked = recommended_entry(budget, (fast, slow), input_tokens=32_768)

    assert picked is not None
    assert (picked[0].id, picked[1]) == ("fast-prefill", "speed-gated-quality")


def test_missing_prompt_workload_keeps_decode_only_floor_behavior():
    """Measured prefill cannot alter the established policy without input workload data."""
    budget = _discrete(128)
    fast = _test_entry(entry_id="fast-decode", quality=50, size_gb=1, prefill_tok_s=1_000)
    slow = _test_entry(entry_id="slow-decode", quality=100, size_gb=40, prefill_tok_s=10)

    picked = recommended_entry(budget, (fast, slow))

    assert predicted_agent_turn_latency_s(fast, fast.variants[0], budget) is None
    assert picked is not None
    assert (picked[0].id, picked[1]) == ("slow-decode", "best-quality-resident")


def test_invalid_prefill_cost_fails_open_to_decode_only_behavior():
    budget = _discrete(128)
    fast = _test_entry(entry_id="fast-decode", quality=50, size_gb=1,
                       prefill_tok_s=float("nan"))
    slow = _test_entry(entry_id="slow-decode", quality=100, size_gb=40)

    picked = recommended_entry(budget, (fast, slow))

    assert predicted_agent_turn_latency_s(fast, fast.variants[0], budget) is None
    assert picked is not None
    assert (picked[0].id, picked[1]) == ("slow-decode", "best-quality-resident")


def test_prefill_latency_orders_fastest_resident_when_none_are_pleasant():
    """With complete prompt data, the fallback orders by turn latency, not decode alone."""
    budget = _discrete(128)
    faster_turn = _test_entry(
        entry_id="faster-turn", quality=50, size_gb=10, prefill_tok_s=10)
    slower_turn = _test_entry(
        entry_id="slower-turn", quality=100, size_gb=1, prefill_tok_s=5)

    picked = recommended_entry(budget, (faster_turn, slower_turn), input_tokens=32_768)

    assert picked is not None
    assert (picked[0].id, picked[1]) == ("faster-turn", "fastest-resident")
